CREATE TABLE USER (
ID INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
TELEGRAM_USER_NAME VARCHAR(32) NOT NULL,
FIRST_NAME VARCHAR(64),
LAST_NAME VARCHAR(64),
PHONE_NUMBER VARCHAR(32),
UNIQUE_TELEGRAM_USER_ID INT(11) UNIQUE
);

CREATE TABLE API_KEY (
ID INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
USER_ID INT(11) UNSIGNED,
PUBLIC_KEY VARCHAR(200) NOT NULL,
SECRET_KEY VARCHAR(200) NOT NULL,
ACTIVE TINYINT(1),
STATUS ENUM('ONE','ANOTHER'),
CAN_TRADE TINYINT(1),
CAN_WITHDRAW TINYINT(1),
CAN_DEPOSIT TINYINT(1),
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);